# Generated by Django 2.1.7 on 2019-03-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20190310_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='unique_no',
            new_name='my_no',
        ),
    ]
