# Generated by Django 2.1.7 on 2019-03-10 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_auto_20190310_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='my_no',
            field=models.IntegerField(default=0, max_length=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
